[package]
name = "dummy"
version = "0.1.0"
authors = ["Agustin Chiappe Berrini <jnieve@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.0.1"
lachesis-rs = { path = "../lachesis-rs" }
rand = "0.6.0"
ring = "0.13.4"
untrusted = "0.6.2"

